export interface SeedTopicAlias {
  label: string
  topicLabel: string
}

export interface SeedTopicRelation {
  childLabel: string
  parentLabel: string
}

export const seedTopicLabels = [
  'Array',
  'String',
  'Hash Table',
  'Math',
  'Dynamic Programming',
  'Sorting',
  'Greedy',
  'Binary Search',
  'Depth-First Search',
  'Database',
  'Bit Manipulation',
  'Matrix',
  'Tree',
  'Breadth-First Search',
  'Two Pointers',
  'Prefix Sum',
  'Heap (Priority Queue)',
  'Intervals',
  'Simulation',
  'Counting',
  'Graph Theory',
  'Binary Tree',
  'Stack',
  'Sliding Window',
  'Enumeration',
  'Design',
  'Backtracking',
  'Union-Find',
  'Number Theory',
  'Linked List',
  'Segment Tree',
  'Ordered Set',
  'Monotonic Stack',
  'Divide and Conquer',
  'Combinatorics',
  'Trie',
  'Bitmask',
  'Queue',
  'Recursion',
  'Geometry',
  'Binary Indexed Tree',
  'Hash Function',
  'Memoization',
  'Binary Search Tree',
  'Topological Sort',
  'Shortest Path',
  'String Matching',
  'Rolling Hash',
  'Game Theory',
  'Interactive',
  'Data Stream',
  'Monotonic Queue',
  'Brainteaser',
  'Doubly-Linked List',
  'Merge Sort',
  'Randomized',
  'Counting Sort',
  'Iterator',
  'Concurrency',
  'Suffix Array',
  'Quickselect',
  'Sweep Line',
  'Probability and Statistics',
  'Minimum Spanning Tree',
  'Bucket Sort',
  'Shell',
  'Reservoir Sampling',
  'Eulerian Circuit',
  'Radix Sort',
  'Strongly Connected Component',
  'Rejection Sampling',
  'Biconnected Component',
] as const

export const seedTopicAliases = [
  { label: 'Arrays', topicLabel: 'Array' },
  { label: 'Arrays & Hashing', topicLabel: 'Array' },
  { label: 'Array / String', topicLabel: 'Array' },
  { label: 'Hash Map', topicLabel: 'Hash Table' },
  { label: 'Hash Set', topicLabel: 'Hash Table' },
  { label: 'Hash Map / Set', topicLabel: 'Hash Table' },
  { label: 'Hash Maps And Sets', topicLabel: 'Hash Table' },
  { label: 'DP', topicLabel: 'Dynamic Programming' },
  { label: '1-D Dynamic Programming', topicLabel: 'Dynamic Programming' },
  { label: '2-D Dynamic Programming', topicLabel: 'Dynamic Programming' },
  { label: 'DFS', topicLabel: 'Depth-First Search' },
  { label: 'Graphs - DFS', topicLabel: 'Depth-First Search' },
  { label: 'Binary Tree - DFS', topicLabel: 'Depth-First Search' },
  { label: 'BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Graphs - BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Binary Tree - BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Graph', topicLabel: 'Graph Theory' },
  { label: 'Graphs', topicLabel: 'Graph Theory' },
  { label: 'Advanced Graphs', topicLabel: 'Graph Theory' },
  { label: 'Heap', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Heaps', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Priority Queue', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Heap / Priority Queue', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Trees', topicLabel: 'Tree' },
  { label: 'Tries', topicLabel: 'Trie' },
  { label: 'Stacks', topicLabel: 'Stack' },
  { label: 'Linked Lists', topicLabel: 'Linked List' },
  { label: 'Prefix Sums', topicLabel: 'Prefix Sum' },
  { label: 'Union Find', topicLabel: 'Union-Find' },
  { label: 'Fenwick Tree', topicLabel: 'Binary Indexed Tree' },
  { label: 'Binary', topicLabel: 'Bit Manipulation' },
  { label: 'Bit Mask', topicLabel: 'Bitmask' },
  { label: 'KMP', topicLabel: 'String Matching' },
  { label: 'Rabin-Karp', topicLabel: 'String Matching' },
  { label: 'MST', topicLabel: 'Minimum Spanning Tree' },
  { label: 'SCC', topicLabel: 'Strongly Connected Component' },
  { label: 'Fast And Slow Pointers', topicLabel: 'Two Pointers' },
  { label: 'Sort And Search', topicLabel: 'Sorting' },
  { label: 'Math And Geometry', topicLabel: 'Math' },
] satisfies readonly SeedTopicAlias[]

export const seedTopicRelations = [
  { childLabel: 'Binary Tree', parentLabel: 'Tree' },
  { childLabel: 'Binary Search Tree', parentLabel: 'Binary Tree' },
  { childLabel: 'Depth-First Search', parentLabel: 'Graph Theory' },
  { childLabel: 'Depth-First Search', parentLabel: 'Tree' },
  { childLabel: 'Depth-First Search', parentLabel: 'Binary Tree' },
  { childLabel: 'Breadth-First Search', parentLabel: 'Graph Theory' },
  { childLabel: 'Breadth-First Search', parentLabel: 'Tree' },
  { childLabel: 'Breadth-First Search', parentLabel: 'Binary Tree' },
  { childLabel: 'Topological Sort', parentLabel: 'Graph Theory' },
  { childLabel: 'Shortest Path', parentLabel: 'Graph Theory' },
  { childLabel: 'Minimum Spanning Tree', parentLabel: 'Graph Theory' },
  { childLabel: 'Eulerian Circuit', parentLabel: 'Graph Theory' },
  { childLabel: 'Strongly Connected Component', parentLabel: 'Graph Theory' },
  { childLabel: 'Biconnected Component', parentLabel: 'Graph Theory' },
  { childLabel: 'Union-Find', parentLabel: 'Graph Theory' },
  { childLabel: 'Rolling Hash', parentLabel: 'String' },
  { childLabel: 'String Matching', parentLabel: 'String' },
  { childLabel: 'Suffix Array', parentLabel: 'String' },
  { childLabel: 'Monotonic Stack', parentLabel: 'Stack' },
  { childLabel: 'Monotonic Queue', parentLabel: 'Queue' },
  { childLabel: 'Merge Sort', parentLabel: 'Sorting' },
  { childLabel: 'Counting Sort', parentLabel: 'Sorting' },
  { childLabel: 'Radix Sort', parentLabel: 'Sorting' },
  { childLabel: 'Bucket Sort', parentLabel: 'Sorting' },
  { childLabel: 'Quickselect', parentLabel: 'Divide and Conquer' },
  { childLabel: 'Merge Sort', parentLabel: 'Divide and Conquer' },
  { childLabel: 'Combinatorics', parentLabel: 'Math' },
  { childLabel: 'Number Theory', parentLabel: 'Math' },
  { childLabel: 'Probability and Statistics', parentLabel: 'Math' },
  { childLabel: 'Geometry', parentLabel: 'Math' },
  { childLabel: 'Memoization', parentLabel: 'Dynamic Programming' },
  { childLabel: 'Memoization', parentLabel: 'Recursion' },
  { childLabel: 'Bitmask', parentLabel: 'Bit Manipulation' },
  { childLabel: 'Doubly-Linked List', parentLabel: 'Linked List' },
] satisfies readonly SeedTopicRelation[]
