export interface SeedTopic {
  id: string
  label: string
}

export interface SeedTopicAlias {
  label: string
  aliasKey: string
  topicId: string
}

export interface SeedTopicRelation {
  sourceTopicId: string
  targetTopicId: string
  kind: 'broader' | 'applies-to'
}

export const seedTopics = [
  { id: 'array', label: 'Array' },
  { id: 'string', label: 'String' },
  { id: 'hash-table', label: 'Hash Table' },
  { id: 'math', label: 'Math' },
  { id: 'dynamic-programming', label: 'Dynamic Programming' },
  { id: 'sorting', label: 'Sorting' },
  { id: 'greedy', label: 'Greedy' },
  { id: 'binary-search', label: 'Binary Search' },
  { id: 'depth-first-search', label: 'Depth-First Search' },
  { id: 'database', label: 'Database' },
  { id: 'bit-manipulation', label: 'Bit Manipulation' },
  { id: 'matrix', label: 'Matrix' },
  { id: 'tree', label: 'Tree' },
  { id: 'breadth-first-search', label: 'Breadth-First Search' },
  { id: 'two-pointers', label: 'Two Pointers' },
  { id: 'prefix-sum', label: 'Prefix Sum' },
  { id: 'heap-priority-queue', label: 'Heap (Priority Queue)' },
  { id: 'intervals', label: 'Intervals' },
  { id: 'simulation', label: 'Simulation' },
  { id: 'counting', label: 'Counting' },
  { id: 'graph-theory', label: 'Graph Theory' },
  { id: 'binary-tree', label: 'Binary Tree' },
  { id: 'stack', label: 'Stack' },
  { id: 'sliding-window', label: 'Sliding Window' },
  { id: 'enumeration', label: 'Enumeration' },
  { id: 'design', label: 'Design' },
  { id: 'backtracking', label: 'Backtracking' },
  { id: 'union-find', label: 'Union-Find' },
  { id: 'number-theory', label: 'Number Theory' },
  { id: 'linked-list', label: 'Linked List' },
  { id: 'segment-tree', label: 'Segment Tree' },
  { id: 'ordered-set', label: 'Ordered Set' },
  { id: 'monotonic-stack', label: 'Monotonic Stack' },
  { id: 'divide-and-conquer', label: 'Divide and Conquer' },
  { id: 'combinatorics', label: 'Combinatorics' },
  { id: 'trie', label: 'Trie' },
  { id: 'bitmask', label: 'Bitmask' },
  { id: 'queue', label: 'Queue' },
  { id: 'recursion', label: 'Recursion' },
  { id: 'geometry', label: 'Geometry' },
  { id: 'binary-indexed-tree', label: 'Binary Indexed Tree' },
  { id: 'hash-function', label: 'Hash Function' },
  { id: 'memoization', label: 'Memoization' },
  { id: 'binary-search-tree', label: 'Binary Search Tree' },
  { id: 'topological-sort', label: 'Topological Sort' },
  { id: 'shortest-path', label: 'Shortest Path' },
  { id: 'string-matching', label: 'String Matching' },
  { id: 'rolling-hash', label: 'Rolling Hash' },
  { id: 'game-theory', label: 'Game Theory' },
  { id: 'interactive', label: 'Interactive' },
  { id: 'data-stream', label: 'Data Stream' },
  { id: 'monotonic-queue', label: 'Monotonic Queue' },
  { id: 'brainteaser', label: 'Brainteaser' },
  { id: 'doubly-linked-list', label: 'Doubly-Linked List' },
  { id: 'merge-sort', label: 'Merge Sort' },
  { id: 'randomized', label: 'Randomized' },
  { id: 'counting-sort', label: 'Counting Sort' },
  { id: 'iterator', label: 'Iterator' },
  { id: 'concurrency', label: 'Concurrency' },
  { id: 'suffix-array', label: 'Suffix Array' },
  { id: 'quickselect', label: 'Quickselect' },
  { id: 'sweep-line', label: 'Sweep Line' },
  { id: 'probability-and-statistics', label: 'Probability and Statistics' },
  { id: 'minimum-spanning-tree', label: 'Minimum Spanning Tree' },
  { id: 'bucket-sort', label: 'Bucket Sort' },
  { id: 'shell', label: 'Shell' },
  { id: 'reservoir-sampling', label: 'Reservoir Sampling' },
  { id: 'eulerian-circuit', label: 'Eulerian Circuit' },
  { id: 'radix-sort', label: 'Radix Sort' },
  { id: 'strongly-connected-component', label: 'Strongly Connected Component' },
  { id: 'rejection-sampling', label: 'Rejection Sampling' },
  { id: 'biconnected-component', label: 'Biconnected Component' },
  { id: 'meet-in-the-middle', label: 'Meet in the Middle' },
  { id: 'minimax', label: 'Minimax' },
  { id: 'kmp', label: 'KMP' },
  { id: 'rabin-karp', label: 'Rabin-Karp' },
  { id: '1-d-dynamic-programming', label: '1-D Dynamic Programming' },
  { id: '2-d-dynamic-programming', label: '2-D Dynamic Programming' },
  { id: 'fast-and-slow-pointers', label: 'Fast And Slow Pointers' },
  { id: 'hash-map', label: 'Hash Map' },
  { id: 'hash-set', label: 'Hash Set' },
] as const satisfies readonly SeedTopic[]

export const seedTopicLabels = seedTopics.map(({ label }) => label)

export const seedTopicAliases = [
  { label: 'Arrays', aliasKey: 'arrays', topicId: 'array' },
  { label: 'DP', aliasKey: 'dp', topicId: 'dynamic-programming' },
  { label: 'DFS', aliasKey: 'dfs', topicId: 'depth-first-search' },
  { label: 'BFS', aliasKey: 'bfs', topicId: 'breadth-first-search' },
  { label: 'Graph', aliasKey: 'graph', topicId: 'graph-theory' },
  { label: 'Graphs', aliasKey: 'graphs', topicId: 'graph-theory' },
  { label: 'Heap', aliasKey: 'heap', topicId: 'heap-priority-queue' },
  { label: 'Heaps', aliasKey: 'heaps', topicId: 'heap-priority-queue' },
  {
    label: 'Priority Queue',
    aliasKey: 'priority queue',
    topicId: 'heap-priority-queue',
  },
  {
    label: 'Heap / Priority Queue',
    aliasKey: 'heap / priority queue',
    topicId: 'heap-priority-queue',
  },
  { label: 'Trees', aliasKey: 'trees', topicId: 'tree' },
  { label: 'Tries', aliasKey: 'tries', topicId: 'trie' },
  { label: 'Stacks', aliasKey: 'stacks', topicId: 'stack' },
  { label: 'Linked Lists', aliasKey: 'linked lists', topicId: 'linked-list' },
  { label: 'Prefix Sums', aliasKey: 'prefix sums', topicId: 'prefix-sum' },
  { label: 'Union Find', aliasKey: 'union find', topicId: 'union-find' },
  {
    label: 'Disjoint Set Union',
    aliasKey: 'disjoint set union',
    topicId: 'union-find',
  },
  { label: 'DSU', aliasKey: 'dsu', topicId: 'union-find' },
  {
    label: 'Fenwick Tree',
    aliasKey: 'fenwick tree',
    topicId: 'binary-indexed-tree',
  },
  { label: 'BIT', aliasKey: 'bit', topicId: 'binary-indexed-tree' },
  { label: 'BST', aliasKey: 'bst', topicId: 'binary-search-tree' },
  { label: 'Bit Mask', aliasKey: 'bit mask', topicId: 'bitmask' },
  { label: 'MST', aliasKey: 'mst', topicId: 'minimum-spanning-tree' },
  {
    label: 'SCC',
    aliasKey: 'scc',
    topicId: 'strongly-connected-component',
  },
  {
    label: 'Knuth-Morris-Pratt',
    aliasKey: 'knuth-morris-pratt',
    topicId: 'kmp',
  },
  {
    label: '1-D DP',
    aliasKey: '1-d dp',
    topicId: '1-d-dynamic-programming',
  },
  {
    label: '2-D DP',
    aliasKey: '2-d dp',
    topicId: '2-d-dynamic-programming',
  },
] as const satisfies readonly SeedTopicAlias[]

export const seedTopicRelations = [
  { sourceTopicId: 'binary-tree', targetTopicId: 'tree', kind: 'broader' },
  {
    sourceTopicId: 'binary-search-tree',
    targetTopicId: 'binary-tree',
    kind: 'broader',
  },
  { sourceTopicId: 'segment-tree', targetTopicId: 'tree', kind: 'broader' },
  { sourceTopicId: 'trie', targetTopicId: 'tree', kind: 'broader' },
  {
    sourceTopicId: 'topological-sort',
    targetTopicId: 'graph-theory',
    kind: 'broader',
  },
  {
    sourceTopicId: 'shortest-path',
    targetTopicId: 'graph-theory',
    kind: 'broader',
  },
  {
    sourceTopicId: 'minimum-spanning-tree',
    targetTopicId: 'graph-theory',
    kind: 'broader',
  },
  {
    sourceTopicId: 'eulerian-circuit',
    targetTopicId: 'graph-theory',
    kind: 'broader',
  },
  {
    sourceTopicId: 'strongly-connected-component',
    targetTopicId: 'graph-theory',
    kind: 'broader',
  },
  {
    sourceTopicId: 'biconnected-component',
    targetTopicId: 'graph-theory',
    kind: 'broader',
  },
  {
    sourceTopicId: 'string-matching',
    targetTopicId: 'string',
    kind: 'broader',
  },
  { sourceTopicId: 'suffix-array', targetTopicId: 'string', kind: 'broader' },
  { sourceTopicId: 'kmp', targetTopicId: 'string-matching', kind: 'broader' },
  {
    sourceTopicId: 'rabin-karp',
    targetTopicId: 'string-matching',
    kind: 'broader',
  },
  { sourceTopicId: 'hash-map', targetTopicId: 'hash-table', kind: 'broader' },
  { sourceTopicId: 'hash-set', targetTopicId: 'hash-table', kind: 'broader' },
  { sourceTopicId: 'monotonic-stack', targetTopicId: 'stack', kind: 'broader' },
  { sourceTopicId: 'monotonic-queue', targetTopicId: 'queue', kind: 'broader' },
  {
    sourceTopicId: 'doubly-linked-list',
    targetTopicId: 'linked-list',
    kind: 'broader',
  },
  { sourceTopicId: 'merge-sort', targetTopicId: 'sorting', kind: 'broader' },
  {
    sourceTopicId: 'merge-sort',
    targetTopicId: 'divide-and-conquer',
    kind: 'broader',
  },
  { sourceTopicId: 'counting-sort', targetTopicId: 'sorting', kind: 'broader' },
  { sourceTopicId: 'bucket-sort', targetTopicId: 'sorting', kind: 'broader' },
  { sourceTopicId: 'radix-sort', targetTopicId: 'sorting', kind: 'broader' },
  {
    sourceTopicId: 'quickselect',
    targetTopicId: 'divide-and-conquer',
    kind: 'broader',
  },
  { sourceTopicId: 'number-theory', targetTopicId: 'math', kind: 'broader' },
  { sourceTopicId: 'combinatorics', targetTopicId: 'math', kind: 'broader' },
  { sourceTopicId: 'geometry', targetTopicId: 'math', kind: 'broader' },
  {
    sourceTopicId: 'probability-and-statistics',
    targetTopicId: 'math',
    kind: 'broader',
  },
  {
    sourceTopicId: 'bitmask',
    targetTopicId: 'bit-manipulation',
    kind: 'broader',
  },
  {
    sourceTopicId: '1-d-dynamic-programming',
    targetTopicId: 'dynamic-programming',
    kind: 'broader',
  },
  {
    sourceTopicId: '2-d-dynamic-programming',
    targetTopicId: 'dynamic-programming',
    kind: 'broader',
  },
  {
    sourceTopicId: 'fast-and-slow-pointers',
    targetTopicId: 'two-pointers',
    kind: 'broader',
  },
  {
    sourceTopicId: 'depth-first-search',
    targetTopicId: 'tree',
    kind: 'applies-to',
  },
  {
    sourceTopicId: 'depth-first-search',
    targetTopicId: 'graph-theory',
    kind: 'applies-to',
  },
  {
    sourceTopicId: 'breadth-first-search',
    targetTopicId: 'tree',
    kind: 'applies-to',
  },
  {
    sourceTopicId: 'breadth-first-search',
    targetTopicId: 'graph-theory',
    kind: 'applies-to',
  },
  {
    sourceTopicId: 'union-find',
    targetTopicId: 'graph-theory',
    kind: 'applies-to',
  },
  {
    sourceTopicId: 'rolling-hash',
    targetTopicId: 'string',
    kind: 'applies-to',
  },
  {
    sourceTopicId: 'memoization',
    targetTopicId: 'dynamic-programming',
    kind: 'applies-to',
  },
  {
    sourceTopicId: 'memoization',
    targetTopicId: 'recursion',
    kind: 'applies-to',
  },
] as const satisfies readonly SeedTopicRelation[]
