export const legacyTopicAliasRows = [
  { label: 'Arrays', topicLabel: 'Array' },
  { label: 'Arrays & Hashing', topicLabel: 'Array' },
  { label: 'Array / String', topicLabel: 'Array' },
  { label: 'Hash Map', topicLabel: 'Hash Table' },
  { label: 'Hash Set', topicLabel: 'Hash Table' },
  { label: 'Hash Map / Set', topicLabel: 'Hash Table' },
  { label: 'Hash Maps And Sets', topicLabel: 'Hash Table' },
  { label: 'DP', topicLabel: 'Dynamic Programming' },
  { label: '1-D Dynamic Programming', topicLabel: 'Dynamic Programming' },
  { label: '2-D Dynamic Programming', topicLabel: 'Dynamic Programming' },
  { label: 'DFS', topicLabel: 'Depth-First Search' },
  { label: 'Graphs - DFS', topicLabel: 'Depth-First Search' },
  { label: 'Binary Tree - DFS', topicLabel: 'Depth-First Search' },
  { label: 'BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Graphs - BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Binary Tree - BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Graph', topicLabel: 'Graph Theory' },
  { label: 'Graphs', topicLabel: 'Graph Theory' },
  { label: 'Advanced Graphs', topicLabel: 'Graph Theory' },
  { label: 'Heap', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Heaps', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Priority Queue', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Heap / Priority Queue', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Trees', topicLabel: 'Tree' },
  { label: 'Tries', topicLabel: 'Trie' },
  { label: 'Stacks', topicLabel: 'Stack' },
  { label: 'Linked Lists', topicLabel: 'Linked List' },
  { label: 'Prefix Sums', topicLabel: 'Prefix Sum' },
  { label: 'Union Find', topicLabel: 'Union-Find' },
  { label: 'Fenwick Tree', topicLabel: 'Binary Indexed Tree' },
  { label: 'Binary', topicLabel: 'Bit Manipulation' },
  { label: 'Bit Mask', topicLabel: 'Bitmask' },
  { label: 'KMP', topicLabel: 'String Matching' },
  { label: 'Rabin-Karp', topicLabel: 'String Matching' },
  { label: 'MST', topicLabel: 'Minimum Spanning Tree' },
  { label: 'SCC', topicLabel: 'Strongly Connected Component' },
  { label: 'Fast And Slow Pointers', topicLabel: 'Two Pointers' },
  { label: 'Sort And Search', topicLabel: 'Sorting' },
  { label: 'Math And Geometry', topicLabel: 'Math' },
] as const
