export const topicReconciliationVersion = 1

export const legacyTopicAliasRows = [
  { label: 'Arrays', topicLabel: 'Array' },
  { label: 'Arrays & Hashing', topicLabel: 'Array' },
  { label: 'Array / String', topicLabel: 'Array' },
  { label: 'Hash Map', topicLabel: 'Hash Table' },
  { label: 'Hash Set', topicLabel: 'Hash Table' },
  { label: 'Hash Map / Set', topicLabel: 'Hash Table' },
  { label: 'Hash Maps And Sets', topicLabel: 'Hash Table' },
  { label: 'DP', topicLabel: 'Dynamic Programming' },
  { label: '1-D Dynamic Programming', topicLabel: 'Dynamic Programming' },
  { label: '2-D Dynamic Programming', topicLabel: 'Dynamic Programming' },
  { label: 'DFS', topicLabel: 'Depth-First Search' },
  { label: 'Graphs - DFS', topicLabel: 'Depth-First Search' },
  { label: 'Binary Tree - DFS', topicLabel: 'Depth-First Search' },
  { label: 'BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Graphs - BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Binary Tree - BFS', topicLabel: 'Breadth-First Search' },
  { label: 'Graph', topicLabel: 'Graph Theory' },
  { label: 'Graphs', topicLabel: 'Graph Theory' },
  { label: 'Advanced Graphs', topicLabel: 'Graph Theory' },
  { label: 'Heap', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Heaps', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Priority Queue', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Heap / Priority Queue', topicLabel: 'Heap (Priority Queue)' },
  { label: 'Trees', topicLabel: 'Tree' },
  { label: 'Tries', topicLabel: 'Trie' },
  { label: 'Stacks', topicLabel: 'Stack' },
  { label: 'Linked Lists', topicLabel: 'Linked List' },
  { label: 'Prefix Sums', topicLabel: 'Prefix Sum' },
  { label: 'Union Find', topicLabel: 'Union-Find' },
  { label: 'Fenwick Tree', topicLabel: 'Binary Indexed Tree' },
  { label: 'Binary', topicLabel: 'Bit Manipulation' },
  { label: 'Bit Mask', topicLabel: 'Bitmask' },
  { label: 'KMP', topicLabel: 'String Matching' },
  { label: 'Rabin-Karp', topicLabel: 'String Matching' },
  { label: 'MST', topicLabel: 'Minimum Spanning Tree' },
  { label: 'SCC', topicLabel: 'Strongly Connected Component' },
  { label: 'Fast And Slow Pointers', topicLabel: 'Two Pointers' },
  { label: 'Sort And Search', topicLabel: 'Sorting' },
  { label: 'Math And Geometry', topicLabel: 'Math' },
] as const

export const legacyTopicBroaderEdges = [
  {
    id: 'binary-tree:tree',
    sourceTopicId: 'binary-tree',
    targetTopicId: 'tree',
  },
  {
    id: 'binary-search-tree:binary-tree',
    sourceTopicId: 'binary-search-tree',
    targetTopicId: 'binary-tree',
  },
  {
    id: 'depth-first-search:graph-theory',
    sourceTopicId: 'depth-first-search',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'depth-first-search:tree',
    sourceTopicId: 'depth-first-search',
    targetTopicId: 'tree',
  },
  {
    id: 'depth-first-search:binary-tree',
    sourceTopicId: 'depth-first-search',
    targetTopicId: 'binary-tree',
  },
  {
    id: 'breadth-first-search:graph-theory',
    sourceTopicId: 'breadth-first-search',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'breadth-first-search:tree',
    sourceTopicId: 'breadth-first-search',
    targetTopicId: 'tree',
  },
  {
    id: 'breadth-first-search:binary-tree',
    sourceTopicId: 'breadth-first-search',
    targetTopicId: 'binary-tree',
  },
  {
    id: 'topological-sort:graph-theory',
    sourceTopicId: 'topological-sort',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'shortest-path:graph-theory',
    sourceTopicId: 'shortest-path',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'minimum-spanning-tree:graph-theory',
    sourceTopicId: 'minimum-spanning-tree',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'eulerian-circuit:graph-theory',
    sourceTopicId: 'eulerian-circuit',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'strongly-connected-component:graph-theory',
    sourceTopicId: 'strongly-connected-component',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'biconnected-component:graph-theory',
    sourceTopicId: 'biconnected-component',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'union-find:graph-theory',
    sourceTopicId: 'union-find',
    targetTopicId: 'graph-theory',
  },
  {
    id: 'rolling-hash:string',
    sourceTopicId: 'rolling-hash',
    targetTopicId: 'string',
  },
  {
    id: 'string-matching:string',
    sourceTopicId: 'string-matching',
    targetTopicId: 'string',
  },
  {
    id: 'suffix-array:string',
    sourceTopicId: 'suffix-array',
    targetTopicId: 'string',
  },
  {
    id: 'monotonic-stack:stack',
    sourceTopicId: 'monotonic-stack',
    targetTopicId: 'stack',
  },
  {
    id: 'monotonic-queue:queue',
    sourceTopicId: 'monotonic-queue',
    targetTopicId: 'queue',
  },
  {
    id: 'merge-sort:sorting',
    sourceTopicId: 'merge-sort',
    targetTopicId: 'sorting',
  },
  {
    id: 'counting-sort:sorting',
    sourceTopicId: 'counting-sort',
    targetTopicId: 'sorting',
  },
  {
    id: 'radix-sort:sorting',
    sourceTopicId: 'radix-sort',
    targetTopicId: 'sorting',
  },
  {
    id: 'bucket-sort:sorting',
    sourceTopicId: 'bucket-sort',
    targetTopicId: 'sorting',
  },
  {
    id: 'quickselect:divide-and-conquer',
    sourceTopicId: 'quickselect',
    targetTopicId: 'divide-and-conquer',
  },
  {
    id: 'merge-sort:divide-and-conquer',
    sourceTopicId: 'merge-sort',
    targetTopicId: 'divide-and-conquer',
  },
  {
    id: 'combinatorics:math',
    sourceTopicId: 'combinatorics',
    targetTopicId: 'math',
  },
  {
    id: 'number-theory:math',
    sourceTopicId: 'number-theory',
    targetTopicId: 'math',
  },
  {
    id: 'probability-and-statistics:math',
    sourceTopicId: 'probability-and-statistics',
    targetTopicId: 'math',
  },
  { id: 'geometry:math', sourceTopicId: 'geometry', targetTopicId: 'math' },
  {
    id: 'memoization:dynamic-programming',
    sourceTopicId: 'memoization',
    targetTopicId: 'dynamic-programming',
  },
  {
    id: 'memoization:recursion',
    sourceTopicId: 'memoization',
    targetTopicId: 'recursion',
  },
  {
    id: 'bitmask:bit-manipulation',
    sourceTopicId: 'bitmask',
    targetTopicId: 'bit-manipulation',
  },
  {
    id: 'doubly-linked-list:linked-list',
    sourceTopicId: 'doubly-linked-list',
    targetTopicId: 'linked-list',
  },
] as const
