name: PR Title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - name: Skip validate semantic title for Bolt AI agent
        run: echo "Skipped PR title validation."
